# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version=0.7.0+1.21.1
maven_group=at.petrak
archives_name=paucal
enabled_platforms=fabric,neoforge,quilt

# Minecraft properties
minecraft_version=1.21.1

# Dependencies
architectury_api_version=13.0.2
fabric_loader_version=0.16.3
fabric_api_version=0.103.0+1.21.1
neoforge_version=21.1.31
quilt_loader_version=0.26.4-beta.5
# DNE yet
# quilted_fabric_api_version = 11.0.0-alpha.3+0.100.7-1.21

jankson_version=1.2.2